name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  combined_job:
    name: Basic CI check
    runs-on: ubuntu-latest

    steps:
      - name: Prints Hello World
        run: echo "hello world"
