name: packerCI

on:
  pull_request:
    branches:
      - main

jobs:
  print:
    name: packer CI - Print job
    runs-on: ubuntu-latest

    steps:
      - name: Prints packer CI
        run: echo "packer CI"
