name: sampleCI

on:
  pull_request:
    branches:
      - main

jobs:
  print:
    name: sample CI - print job
    runs-on: ubuntu-latest

    steps:
      - name: Prints Hello World
        run: echo "hello world"
