name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  combined_job:
    name: Prints hello world and installs dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Prints Hello world
        run: echo "Hello World"

      - name: Checkout code
        run: actions/checkout@v2

      - name: Install Node.js dependencies
        run: npm install
