name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  combined_job:
    name: Hello World and Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Prints Hello World
        run: echo "hello world"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: print all MySQL
        run: ls /etc/init.d/

      - name: start mysql
        run: |
          sudo /etc/init.d/mysql start
