name: Integration test

on:
  pull_request:
    branches:
      - main

jobs:
  combined_job:
    name: Install API Dependencies and setup MySQL
    runs-on: ubuntu-latest
    env:
      PORT: "3000"
      MYSQL_HOST: "127.0.0.1"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "Abcd@123"
      MYSQL_DATABASE: "test"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install API dependencies
        run: npm ci

      - name: Start mysql
        run: sudo /etc/init.d/mysql start

      - name: Create and set database
        run: |
          mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;" -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}
          mysql -e "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';" -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}
          mysql -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'localhost';" -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}
          mysql -e "FLUSH PRIVILEGES;" -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}

      - name: Run integration tests
        run: npm run test

      - name: Delete the Database
        run: mysql -e "DROP DATABASE $MYSQL_DATABASE;" -uroot -p${{ secrets.MYSQL_ROOT_PASSWORD }}
