name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  combined_job:
    name: Hello World and Install Dependencies
    runs-on: ubuntu-latest
    env:
      MYSQL_HOST: "localhost"
      MYSQL_USER: "user1"
      MYSQL_PASSWORD: "Abcd@123"
      MYSQL_DATABASE: "test"
      
    steps:
      - name: Prints Hello World
        run: echo "hello world"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install node dependencies
        run: npm ci

      - name: Start mysql
        run: sudo /etc/init.d/mysql start

      - name: Create and set database
        run: |
          # mysql -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;" -uroot -p$santy@mysql
          # mysql -e "CREATE USER IF NOT EXISTS '$MYSQL_USER'@'$MYSQL_HOST' IDENTIFIED BY '$MYSQL_PASSWORD';" -uroot -p$santy@mysql
          # mysql -e "GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$MYSQL_USER'@'$MYSQL_HOST';" -uroot -p$santy@mysql
          # mysql -e "FLUSH PRIVILEGES;" -uroot -p$santy@mysql
          sudo apt-get update
          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password santy@mysql'
          sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password santy@mysql'
          sudo apt-get install -y mysql-server
          sudo systemctl start mysql
          mysql -h 127.0.0.1 -uroot -p'santy@mysql' -e "SHOW DATABASES;"

